import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import AuthProvider from "@/src/context/AuthProvider";
import Header from "@/components/Header";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/AppSidebar";
import { ThemeProvider } from "next-themes";
import { Outfit } from "next/font/google";

const outfit = Outfit({ subsets: ["latin"], variable: "--font-outfit" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} ${outfit.variable} antialiased bg-background text-foreground w-full`}>

        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>

          <AuthProvider>
            <SidebarProvider>
              <AppSidebar />
              <div className="flex flex-col w-full">
                <Header>
                  <SidebarTrigger />
                </Header>
                <main className="flex-1">{children}</main>
              </div>
              <Toaster />
            </SidebarProvider>
          </AuthProvider>

        </ThemeProvider>
      </body>
    </html >
  );
}
